import nunjucks from 'nunjucks';
import { TEMPLATES } from '../templates';

/**
 * The sitemap and search feeds were generated by nunjucks templates that lived
 * in the Hexo project. Those templates are kept verbatim in `src/templates` so
 * the feed formats stay recognisable to anyone who edited them before.
 *
 * Hexo compiled them with `new nunjucks.Environment(null, { autoescape: false,
 * watch: false })` and added the same filters.
 */
const env = new nunjucks.Environment(null, { autoescape: false, watch: false });

env.addFilter('uriencode', (str: string) => encodeURI(str));
env.addFilter('noControlChars', (str: string) => str && str.replace(/[\x00-\x1F\x7F]/g, ''));
env.addFilter('formatDate', (input: Date) => input.toISOString().substring(0, 10));

export function renderTemplate(
	name: keyof typeof TEMPLATES,
	context: Record<string, unknown>,
): string {
	const source = TEMPLATES[name];
	if (source === undefined) throw new Error(`Unknown template: ${name}`);
	return nunjucks.compile(source, env).render(context);
}

/**
 * Hexo handed the templates Warehouse Query objects; they behave like arrays
 * that also expose `.toArray()`. Plain arrays can play the same role.
 */
export function asQuery<T>(items: T[]): T[] & { toArray(): T[] } {
	const arr = items.slice() as T[] & { toArray(): T[] };
	arr.toArray = () => arr;
	return arr;
}
